# src/crm/sf_uploader.py

from simple_salesforce import Salesforce, SalesforceAuthenticationFailed
from config.settings import Config

def get_sf_connection():
    """Establishes and returns the Salesforce connection."""
    try:
        sf = Salesforce(
            username=Config.SF.USERNAME, 
            password=Config.SF.PASSWORD, 
            security_token=Config.SF.SECURITY_TOKEN,
            domain=Config.SF.DOMAIN
        )
        return sf
    except SalesforceAuthenticationFailed as e:
        print(f"❌ Salesforce Authentication Failed. Check your .env file. Error: {e}")
        return None

def push_to_salesforce(lead_payload: dict):
    """
    Checks for duplicates and pushes a cleaned lead payload to Salesforce.
    Expects the dictionary generated by LeadModel.to_salesforce_payload().
    """
    sf = get_sf_connection()
    if not sf:
        return

    email = lead_payload.get("Email")
    company = lead_payload.get("Company")

    # Step 1: Prevent duplicates
    # Query Salesforce to see if this email is already an active Lead or Contact
    if email and email != "no-email@fallback.com":
        query = f"SELECT Id FROM Lead WHERE Email = '{email}'"
        try:
            existing_leads = sf.query(query)
            if existing_leads['totalSize'] > 0:
                print(f"⚠️ Skipping: Lead {email} at {company} already exists in CRM.")
                return
        except Exception as e:
            print(f"⚠️ Error querying Salesforce: {e}")

    # Step 2: Insert net-new lead
    try:
        new_lead = sf.Lead.create(lead_payload)
        print(f"✅ Success: Created Lead {lead_payload.get('FirstName')} {lead_payload.get('LastName')} (ID: {new_lead['id']})")
    except Exception as e:
        print(f"❌ Failed to create lead for {company}. Error: {e}")
